// Writes src/features/map/logos.generated.ts from the pinned `simple-icons` package (MIT, CC0 icon data).
// Run: node apps/web/scripts/gen-logos.mjs   (only when this list or the package version changes)
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const icons = require("simple-icons");
const version = JSON.parse(
  readFileSync(new URL("../node_modules/simple-icons/package.json", import.meta.url), "utf8"),
).version;

/** Display name (as majhi names a datastore, service or stack item) to the Simple Icons slug. */
const NAMES = {
  Postgres: "postgresql",
  MySQL: "mysql",
  MongoDB: "mongodb",
  Redis: "redis",
  RabbitMQ: "rabbitmq",
  Kafka: "apachekafka",
  NATS: "natsdotio",
  Memcached: "memcached",
  Elasticsearch: "elasticsearch",
  ClickHouse: "clickhouse",
  SQLite: "sqlite",
  S3: "amazons3",
  AWS: "amazonaws",
  OpenAI: "openai",
  Anthropic: "anthropic",
  Replicate: "replicate",
  Stripe: "stripe",
  Sentry: "sentry",
  Twilio: "twilio",
  SendGrid: "sendgrid",
  Slack: "slack",
  Resend: "resend",
  GitHub: "github",
  GitLab: "gitlab",
  Bitbucket: "bitbucket",
  Telegram: "telegram",
  "Hacker News": "ycombinator",
  Exa: "exa",
  Firecrawl: "firecrawl",
  "Next.js": "nextdotjs",
  Nuxt: "nuxt",
  React: "react",
  Vue: "vuedotjs",
  Svelte: "svelte",
  SvelteKit: "svelte",
  Angular: "angular",
  NestJS: "nestjs",
  Fastify: "fastify",
  Express: "express",
  Hono: "hono",
  Koa: "koa",
  Django: "django",
  FastAPI: "fastapi",
  Flask: "flask",
  Celery: "celery",
  Node: "nodedotjs",
  Python: "python",
  Docker: "docker",
  Kotlin: "kotlin",
  TypeScript: "typescript",
  JavaScript: "javascript",
  Go: "go",
  Rust: "rust",
  Ruby: "ruby",
  PHP: "php",
  Java: "openjdk",
  Swift: "swift",
  Flutter: "flutter",
  Android: "android",
};

const out = {};
const missing = [];
for (const [name, slug] of Object.entries(NAMES)) {
  const i = icons[`si${slug[0].toUpperCase()}${slug.slice(1)}`];
  if (i === undefined) {
    missing.push(`${name} (${slug})`);
    continue;
  }
  out[name] = { path: i.path, hex: i.hex };
}
// Brands Simple Icons dropped at the owner's request: SVGs from @lobehub/icons-static-svg 1.95.1 (MIT),
// saved in scripts/logos-extra/. Every <path d="..."> of a file is joined into one path.
const EXTRA = {
  OpenAI: { file: "openai.svg", hex: "412991" },
  S3: { file: "aws.svg", hex: "FF9900" },
  AWS: { file: "aws.svg", hex: "FF9900" },
  Exa: { file: "exa.svg", hex: "1F40ED" },
  Firecrawl: { file: "firecrawl.svg", hex: "FA5D19" },
};
for (const [name, { file, hex }] of Object.entries(EXTRA)) {
  if (out[name] !== undefined) continue;
  const svg = readFileSync(new URL(`./logos-extra/${file}`, import.meta.url), "utf8");
  const paths = svg
    .split(' d="')
    .slice(1)
    .map((part) => part.slice(0, part.indexOf('"')));
  if (paths.length === 0) continue;
  out[name] = { path: paths.join(" "), hex };
  const at = missing.findIndex((m) => m.startsWith(`${name} (`));
  if (at !== -1) missing.splice(at, 1);
}
const body = `// Generated by apps/web/scripts/gen-logos.mjs from simple-icons ${version} (MIT) and @lobehub/icons-static-svg 1.95.1 (MIT). Do not edit by hand.
export const LOGOS: Readonly<Record<string, { path: string; hex: string }>> = ${JSON.stringify(out, null, 1)};
`;
writeFileSync(fileURLToPath(new URL("../src/features/map/logos.generated.ts", import.meta.url)), body);
console.log(Object.keys(out).length, "logos; missing:", missing.join(", ") || "none");
