// Writes src/features/map/logos.generated.ts from the pinned `simple-icons` package (MIT, CC0 icon data).
// Run: node apps/web/scripts/gen-logos.mjs   (only when this list or the package version changes)
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const icons = require("simple-icons");
const version = JSON.parse(
  readFileSync(new URL("../node_modules/simple-icons/package.json", import.meta.url), "utf8"),
).version;

/** Display name (as majhi names a datastore, service or stack item) to the Simple Icons slug. */
const NAMES = {
  Postgres: "postgresql",
  MySQL: "mysql",
  MongoDB: "mongodb",
  Redis: "redis",
  RabbitMQ: "rabbitmq",
  Kafka: "apachekafka",
  NATS: "natsdotio",
  Memcached: "memcached",
  Elasticsearch: "elasticsearch",
  ClickHouse: "clickhouse",
  SQLite: "sqlite",
  S3: "amazons3",
  AWS: "amazonaws",
  OpenAI: "openai",
  Anthropic: "anthropic",
  Replicate: "replicate",
  Stripe: "stripe",
  Sentry: "sentry",
  Twilio: "twilio",
  SendGrid: "sendgrid",
  Slack: "slack",
  Resend: "resend",
  GitHub: "github",
  GitLab: "gitlab",
  Bitbucket: "bitbucket",
  Telegram: "telegram",
  "Hacker News": "ycombinator",
  Exa: "exa",
  Firecrawl: "firecrawl",
  "Next.js": "nextdotjs",
  Nuxt: "nuxt",
  React: "react",
  Vue: "vuedotjs",
  Svelte: "svelte",
  SvelteKit: "svelte",
  Angular: "angular",
  NestJS: "nestjs",
  Fastify: "fastify",
  Express: "express",
  Hono: "hono",
  Koa: "koa",
  Django: "django",
  FastAPI: "fastapi",
  Flask: "flask",
  Celery: "celery",
  Node: "nodedotjs",
  Python: "python",
  Docker: "docker",
  Kotlin: "kotlin",
  TypeScript: "typescript",
  JavaScript: "javascript",
  Go: "go",
  Rust: "rust",
  Ruby: "ruby",
  PHP: "php",
  Java: "openjdk",
  Swift: "swift",
  Flutter: "flutter",
  Android: "android",
};

// One logo store for the whole app: public/service-logos/<slug>.svg (the Connections page reads the same
// files). A slug already there is used as is; otherwise it is written there from the pinned simple-icons.
// Brands simple-icons later dropped (OpenAI, Twilio, S3) were saved from simple-icons 11.15.0, and Exa and
// Firecrawl from @lobehub/icons-static-svg 1.95.1 (MIT); see public/service-logos/README.md.
const folder = new URL("../public/service-logos/", import.meta.url);
const SLUG_FIX = { Firecrawl: "firecrawl", Exa: "exa", S3: "amazons3", OpenAI: "openai", Twilio: "twilio" };
const out = {};
const missing = [];
for (const [name, given] of Object.entries(NAMES)) {
  const slug = SLUG_FIX[name] ?? given;
  const file = new URL(`${slug}.svg`, folder);
  let svg;
  try {
    svg = readFileSync(file, "utf8");
  } catch {
    const i = icons[`si${slug[0].toUpperCase()}${slug.slice(1)}`];
    if (i === undefined) {
      missing.push(`${name} (${slug})`);
      continue;
    }
    svg = `<svg fill="#${i.hex}" role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>${i.title}</title><path d="${i.path}"/></svg>\n`;
    writeFileSync(file, svg);
  }
  const paths = svg
    .split(' d="')
    .slice(1)
    .map((part) => part.slice(0, part.indexOf('"')));
  const fillAt = svg.indexOf('fill="#');
  const hex = fillAt === -1 ? "888888" : svg.slice(fillAt + 7, svg.indexOf('"', fillAt + 7));
  if (paths.length === 0) {
    missing.push(`${name} (${slug})`);
    continue;
  }
  out[name] = { path: paths.join(" "), hex, file: `/service-logos/${slug}.svg` };
}
const body = `// Generated by apps/web/scripts/gen-logos.mjs from public/service-logos (one store, see its README). Do not edit by hand.
export const LOGOS: Readonly<Record<string, { path: string; hex: string; file: string }>> = ${JSON.stringify(out, null, 1)};
`;
writeFileSync(fileURLToPath(new URL("../src/features/map/logos.generated.ts", import.meta.url)), body);
console.log(Object.keys(out).length, "logos; missing:", missing.join(", ") || "none");
