/**
 * Every word the Wiki page says that is not a page's own text, in one place so the owner can change it in one
 * edit. Headings are terse, and no heading has a hint line under it.
 */
export const COPY = {
  heading: {
    about: "About",
    stack: "Stack",
    systemDiagram: "System diagram",
    files: "Files",
    talksTo: "Talks to",
    usedInFlows: "Used in flows",
    details: "Details",
    sequence: "Sequence",
    steps: "Steps",
    openItems: "Open items",
    guessed: "Guessed",
    couldNotConfirm: "Could not confirm",
    guessedRoles: "Guessed roles",
    notLinked: "Not linked calls",
    questions: "Questions for you",
    links: "Links",
    whatRuns: "What runs",
    deploy: "Deploy",
  },
  /** The small tag after a page's title. */
  tag: {
    overview: "Project",
    workspaceOverview: "Workspace",
    component: "Component",
    flow: "Flow",
    crossRepoFlow: "Cross-repo flow",
    infra: "Infra",
    deploys: "Deploys",
    gaps: "Gaps",
  },
  /** The groups of the page list. */
  group: {
    overview: "Overview",
    component: "Components",
    flow: "Flows",
    crossRepoFlow: "Cross-repo flows",
    infra: "Infra and deploy",
    deploys: "Deploys",
    gaps: "Gaps",
  },
  /** The title of the single Gaps page, and of an infra page in the list. */
  openItemsTitle: "Open items",
  subline: {
    overview: "About, stack, diagram",
    workspaceOverview: (repos: number, links: number) =>
      `${repos} ${repos === 1 ? "repo" : "repos"}, ${links} ${links === 1 ? "link" : "links"}`,
    infra: "Hosts and deploy",
    deploys: "Where, how and in what order",
    gaps: "To check and answer",
    outOfDate: "out of date",
  },
  stat: {
    builtFrom: "Built from",
    rolesFound: (n: number) => (n === 1 ? "role found" : "roles found"),
    openItems: "open items",
    toCheck: "to check",
    step: (n: number) => (n === 1 ? "step" : "steps"),
    proven: "proven",
    guessed: "guessed",
    repos: (n: number) => (n === 1 ? "repo" : "repos"),
    links: (n: number) => (n === 1 ? "link" : "links"),
    units: (n: number) => (n === 1 ? "unit" : "units"),
  },
  basis: {
    proven: "proven",
    guessed: "guessed",
    provenTitle: "Proven: the cited lines show it",
    guessedTitle: "Guessed: inferred, no file shows it",
    noFile: "no file shows it",
  },
  /** How a link is known, in the words next to it. */
  linkBasis: {
    declared: "declared",
    exact: "exact route match",
    config: "set by config",
    owner: "your answer",
  },
  stale: {
    behind: (n: number) => `${n} commit${n === 1 ? "" : "s"} since this page was built touch`,
    someNewer: "A newer commit changed",
    outOfDate: "It may be out of date.",
    update: "Update this page",
  },
  stack: {
    notFound: "Not found in the code:",
    seeGaps: "See Gaps",
    open: (title: string) => `Open ${title}`,
    readProof: "Read the proof:",
  },
  details: {
    count: (n: number, total: number) => `${n} of ${total} proven`,
  },
  workspace: {
    option: "Whole workspace",
    repoCount: (n: number) => `${n} ${n === 1 ? "repo" : "repos"}`,
    projects: "Projects",
    openWiki: "Open its wiki",
    notBuilt: "not built",
    built: "built",
    behind: (n: number) => `${n} behind`,
  },
  flows: { none: "No flow cites this component." },
  gaps: {
    nothing: "Nothing to check.",
    noRoute: "No route of another project has it.",
    ambiguous: (projects: string) => `More than one project has this route: ${projects}.`,
    answer: "Answer",
    outside: "Outside",
    ignore: "Ignore",
    calledBy: (projects: string) => `Called by ${projects}.`,
    setIn: (keys: string) => `Set in ${keys}.`,
    whatIs: (address: string) => `What is \`${address}\`?`,
    localTo: (scope: string) => `A local address in ${scope}.`,
    right: "Right",
    changeRole: "Change role",
    undo: "Undo",
    confirmed: "Confirmed by you",
    saved: "Saved as your answer",
    waiting: (n: number) => `${n} waiting`,
  },
  ask: {
    projectPlaceholder: "Ask about this project",
    workspacePlaceholder: "Ask about this workspace",
    button: "Ask",
    asking: "Reading the wiki",
    notBuilt: "Asking is not built yet.",
  },
  notBuilt: "Not built yet.",
  failed: {
    group: "Not written",
    mark: "not written",
    flows: "Main flows",
    retry: "Retry",
    pagesTitle: "Pages not written",
    flowsWhy: "The captain's answer could not be read.",
    pagesWhy: "The update did not get to these. Retry writes them again.",
    updateFailed: "Last update failed",
    signedOut: (account: string) => `${account} is signed out`,
  },
  notes: {
    title: "Your notes",
    add: "Add note",
    placeholder: "A correction for this page",
    save: "Save and rewrite page",
    cancel: "Cancel",
    drop: "Drop",
  },
  build: {
    title: "No wiki yet",
    body: "Build reads the code and writes the architecture pages, each claim with the file behind it.",
    button: "Build",
    reading: "Reading the pages",
    running: "Building the wiki for",
    failed: "The build failed",
    again: "Build again",
    signedOut: (account: string) =>
      `${account} writes the wiki and is signed out. Sign in to it, then build again.`,
  },
  diagram: { openFull: "Open full size" },
  table: { unit: "Unit", how: "How", file: "File" },
  settings: {
    upkeep: "Upkeep",
    upkeepWords: "Runs as the Wiki upkeep playbook. Cadence, run history and Run now live in Playbooks.",
    openPlaybook: "Open playbook",
    whenOff: "When it is off",
    noPlaybook: "Not set up yet",
    on: "On",
    off: "Off",
    running: "Running now",
    lastRun: (ago: string) => `Last run ${ago}`,
    held: (why: string) => `Held: ${why}`,
  },
  picker: {
    workspace: "Workspace",
    project: "Project",
  },
} as const;
