import type { ConfigState } from "@majhi/shared";
import { Document } from "yaml";

/** Service in docker-compose.yml that gets the workspace mounts. */
export const SERVER_SERVICE = "server";

export class InvalidConfigError extends Error {
  constructor(readonly errors: string[]) {
    super("majhi.yaml is invalid");
  }
}

/**
 * Renders `docker-compose.override.yml`: one bind mount per workspace root,
 * at the same absolute path inside the container, so paths match everywhere.
 */
export function renderOverride(state: ConfigState): string {
  if (state.status === "invalid") throw new InvalidConfigError(state.errors);
  const roots = state.status === "loaded" ? state.config.workspaces : [];
  const header = [` Generated by majhi from ${state.file}. Do not edit.`, " Run `make up` to regenerate it."];

  if (roots.length === 0) {
    const doc = new Document({ services: {} });
    doc.commentBefore = [
      ...header,
      " No workspace roots in majhi.yaml yet, so there are no extra mounts.",
    ].join("\n");
    return doc.toString();
  }

  // The short `src:dst` form cannot hold a path with a colon. Use the long form for those.
  const volumes = roots.map((root) =>
    root.includes(":") ? { type: "bind", source: root, target: root } : `${root}:${root}`,
  );
  const doc = new Document({ services: { [SERVER_SERVICE]: { volumes } } });
  doc.commentBefore = header.join("\n");
  return doc.toString();
}
