import type { ConfigState } from "@majhi/shared";
import { Document } from "yaml";

/** Service in docker-compose.yml that gets the workspace mounts. */
export const SERVER_SERVICE = "server";

export class InvalidConfigError extends Error {
  constructor(readonly errors: string[]) {
    super("majhi.yaml is invalid");
  }
}

/**
 * A public key mount source. Only `.pub` files may be mounted: OpenSSH reads
 * `<IdentityFile>.pub` to pick the matching key from the agent when the private
 * file is missing, so `IdentitiesOnly yes` works without a private key here.
 */
export function isPublicKeyPath(path: string): boolean {
  return path.startsWith("/") && path.endsWith(".pub") && !path.includes("\n");
}

/**
 * Renders `docker-compose.override.yml`: one bind mount per workspace root,
 * at the same absolute path inside the container, so paths match everywhere,
 * and a read-only mount for each SSH public key the host has. `sshPublicKeys`
 * comes from the host, which alone can tell which files exist. A source that is
 * not a `.pub` path is refused: a private key must never be mounted.
 */
export function renderOverride(
  state: ConfigState,
  sshPublicKeys: readonly string[] = [],
  dockerGid?: number,
): string {
  if (state.status === "invalid") throw new InvalidConfigError(state.errors);
  const roots = state.status === "loaded" ? state.config.workspaces : [];
  const badKey = sshPublicKeys.find((k) => !isPublicKeyPath(k));
  if (badKey !== undefined) throw new Error(`Refusing to mount ${badKey}: only .pub files are mounted`);
  const keys = [...new Set(sshPublicKeys)].sort();
  const header = [` Generated by majhi from ${state.file}. Do not edit.`, " Run `make up` to regenerate it."];

  // majhi starts agent runners through the Docker socket; its group lets the owner's uid use it.
  const groups = dockerGid === undefined ? {} : { group_add: [String(dockerGid)] };

  if (roots.length === 0 && keys.length === 0 && dockerGid === undefined) {
    const doc = new Document({ services: {} });
    doc.commentBefore = [
      ...header,
      " No workspace roots in majhi.yaml yet, so there are no extra mounts.",
    ].join("\n");
    return doc.toString();
  }

  // The short `src:dst` form cannot hold a path with a colon. Use the long form for those.
  const volumes: unknown[] = roots.map((root) =>
    root.includes(":") ? { type: "bind", source: root, target: root } : `${root}:${root}`,
  );
  for (const key of keys) volumes.push({ type: "bind", source: key, target: key, read_only: true });
  const service = volumes.length === 0 ? groups : { volumes, ...groups };
  const doc = new Document({ services: { [SERVER_SERVICE]: service } });
  doc.commentBefore = header.join("\n");
  return doc.toString();
}
