import { describe, expect, it } from "vitest";
import { parse } from "yaml";
import { InvalidConfigError, renderOverride } from "./genOverride.ts";

const base = { file: "/Users/me/.majhi/majhi.yaml", home: "/Users/me" };
/** No SSH agent, so only what a test is about shows. */
const OFF = { sshAgent: "off" };

describe("renderOverride", () => {
  it("mounts every root at the same path, and survives spaces and colons", () => {
    const roots = [
      "/Users/me/Work",
      "/Users/me/My Projects/client work",
      "/Volumes/Ext: Disk/code",
      "/Users/me/#x",
    ];
    const text = renderOverride(
      {
        status: "loaded",
        ...base,
        config: { workspaces: roots, tasksDir: "/Users/me/Work/.majhi" },
      },
      [],
      undefined,
      OFF,
    );

    expect(text).toMatch(/^# Generated by majhi/);
    expect(parse(text)).toEqual({
      services: {
        server: {
          volumes: [
            "/Users/me/Work:/Users/me/Work",
            "/Users/me/My Projects/client work:/Users/me/My Projects/client work",
            { type: "bind", source: "/Volumes/Ext: Disk/code", target: "/Volumes/Ext: Disk/code" },
            "/Users/me/#x:/Users/me/#x",
          ],
        },
      },
    });
  });

  it("mounts SSH public keys read-only at the same path, next to the roots", () => {
    const text = renderOverride(
      {
        status: "loaded",
        ...base,
        config: { workspaces: ["/Users/me/Work"], tasksDir: "/Users/me/Work/.majhi" },
      },
      [
        "/Users/me/.ssh/id_ed25519.pub",
        "/Users/me/.ssh/gitlab-ashik112.pub",
        "/Users/me/.ssh/id_ed25519.pub",
      ],
      undefined,
      OFF,
    );
    expect(parse(text).services.server.volumes).toEqual([
      "/Users/me/Work:/Users/me/Work",
      {
        type: "bind",
        source: "/Users/me/.ssh/gitlab-ashik112.pub",
        target: "/Users/me/.ssh/gitlab-ashik112.pub",
        read_only: true,
      },
      {
        type: "bind",
        source: "/Users/me/.ssh/id_ed25519.pub",
        target: "/Users/me/.ssh/id_ed25519.pub",
        read_only: true,
      },
    ]);
    expect(
      parse(renderOverride({ status: "first-run", ...base }, ["/Users/me/.ssh/id_rsa.pub"], undefined, OFF)),
    ).toEqual({
      services: {
        server: {
          volumes: [
            {
              type: "bind",
              source: "/Users/me/.ssh/id_rsa.pub",
              target: "/Users/me/.ssh/id_rsa.pub",
              read_only: true,
            },
          ],
        },
      },
    });
  });

  it("never mounts a source without the .pub suffix: a private key cannot reach the override", () => {
    const config = { workspaces: ["/Users/me/Work"], tasksDir: "/Users/me/Work/.majhi" };
    for (const bad of [
      "/Users/me/.ssh/id_ed25519",
      "/Users/me/.ssh",
      "id_rsa.pub",
      "/Users/me/.ssh/id_rsa.pub.bak",
    ]) {
      expect(() => renderOverride({ status: "loaded", ...base, config }, [bad])).toThrow(/only \.pub files/);
    }
    const text = renderOverride({ status: "loaded", ...base, config }, ["/Users/me/.ssh/id_rsa.pub"]);
    const volumes = parse(text).services.server.volumes as Array<
      string | { source: string; read_only?: boolean }
    >;
    const sources = volumes.flatMap((v) => (typeof v === "object" && v.read_only ? [v.source] : []));
    expect(sources.every((s) => s.endsWith(".pub"))).toBe(true);
  });

  it("prints a valid override with no mounts on first run", () => {
    const text = renderOverride({ status: "first-run", ...base }, [], undefined, OFF);
    expect(text).toContain("no extra mounts");
    expect(parse(text)).toEqual({ services: {} });
  });

  it("refuses an invalid config", () => {
    expect(() => renderOverride({ status: "invalid", ...base, errors: ["workspaces: Required"] })).toThrow(
      InvalidConfigError,
    );
  });

  it("lets the server use the Docker socket through its group", () => {
    const out = parse(renderOverride({ status: "first-run", ...base }, [], 991, OFF));
    expect(out).toEqual({ services: { server: { group_add: ["991"] } } });
  });
});

describe("renderOverride: the SSH agent", () => {
  const linux = { file: "/home/owner/.majhi/majhi.yaml", home: "/home/owner" };
  const majhiHome = "/home/owner/.majhi";
  const server = (sshAgent: string | undefined) =>
    parse(renderOverride({ status: "first-run", ...linux }, [], undefined, { sshAgent, majhiHome })).services
      .server;

  it("forwards Docker Desktop's and OrbStack's socket when MAJHI_SSH_AGENT is unset or empty", () => {
    // An older helper runs the first update without MAJHI_SSH_AGENT: macOS keeps today's mount.
    for (const value of [undefined, "", "  "]) {
      expect(server(value)).toEqual({
        volumes: ["/run/host-services/ssh-auth.sock:/run/ssh-agent.sock"],
        environment: { SSH_AUTH_SOCK: "/run/ssh-agent.sock" },
      });
    }
    const mac = renderOverride({ status: "first-run", ...base });
    expect(parse(mac).services.server.environment).toEqual({ SSH_AUTH_SOCK: "/run/ssh-agent.sock" });
  });

  it("only points SSH_AUTH_SOCK at a socket under MAJHI_HOME: the ~/.majhi mount already holds it", () => {
    expect(server("/home/owner/.majhi/run/ssh-agent.sock")).toEqual({
      environment: { SSH_AUTH_SOCK: "/home/owner/.majhi/run/ssh-agent.sock" },
    });
    expect(server("/home/owner/.majhi/run/../run/ssh-agent.sock")).toEqual({
      environment: { SSH_AUTH_SOCK: "/home/owner/.majhi/run/ssh-agent.sock" },
    });
  });

  it("mounts a socket that only looks like it is under MAJHI_HOME", () => {
    expect(server("/home/owner/.majhi-old/ssh-agent.sock")).toEqual({
      volumes: ["/home/owner/.majhi-old/ssh-agent.sock:/run/ssh-agent.sock"],
      environment: { SSH_AUTH_SOCK: "/run/ssh-agent.sock" },
    });
    expect(server("/home/owner/.majhi/../.ssh/agent.sock")).toEqual({
      volumes: ["/home/owner/.ssh/agent.sock:/run/ssh-agent.sock"],
      environment: { SSH_AUTH_SOCK: "/run/ssh-agent.sock" },
    });
  });

  it("mounts any other socket at /run/ssh-agent.sock, in the long form when the path has a colon", () => {
    expect(server("/Users/owner/.ssh/agent socket")).toEqual({
      volumes: ["/Users/owner/.ssh/agent socket:/run/ssh-agent.sock"],
      environment: { SSH_AUTH_SOCK: "/run/ssh-agent.sock" },
    });
    expect(server("/run/user/1000/ssh:agent.sock")).toEqual({
      volumes: [{ type: "bind", source: "/run/user/1000/ssh:agent.sock", target: "/run/ssh-agent.sock" }],
      environment: { SSH_AUTH_SOCK: "/run/ssh-agent.sock" },
    });
  });

  it("puts the agent after the roots and keys, next to the Docker group", () => {
    const text = renderOverride(
      {
        status: "loaded",
        ...linux,
        config: { workspaces: ["/home/owner/code"], tasksDir: "/home/owner/code/.majhi" },
      },
      ["/home/owner/.ssh/id_ed25519.pub"],
      991,
      { sshAgent: "/tmp/ssh-acme/agent.42", majhiHome },
    );
    expect(parse(text).services.server).toEqual({
      volumes: [
        "/home/owner/code:/home/owner/code",
        {
          type: "bind",
          source: "/home/owner/.ssh/id_ed25519.pub",
          target: "/home/owner/.ssh/id_ed25519.pub",
          read_only: true,
        },
        "/tmp/ssh-acme/agent.42:/run/ssh-agent.sock",
      ],
      environment: { SSH_AUTH_SOCK: "/run/ssh-agent.sock" },
      group_add: ["991"],
    });
  });

  it("adds no agent at all with off", () => {
    expect(server("off")).toBeUndefined();
  });

  it("refuses a relative path or one with a line break", () => {
    for (const bad of ["run/ssh-agent.sock", "~/.majhi/run/ssh-agent.sock", "/tmp/a\nb.sock", "OFF"]) {
      expect(() => server(bad)).toThrow(/MAJHI_SSH_AGENT must be an absolute path/);
    }
  });
});

describe("renderOverride: Laya's GPU", () => {
  const laya = (layaGpu: string | undefined) =>
    parse(renderOverride({ status: "first-run", ...base }, [], undefined, { ...OFF, layaGpu })).services.laya;

  it("gives Laya every NVIDIA GPU and tells laya-serve to use CUDA", () => {
    for (const value of ["nvidia", " NVIDIA "]) {
      expect(laya(value)).toEqual({
        environment: { LAYA_DEVICE: "cuda" },
        deploy: {
          resources: {
            reservations: { devices: [{ driver: "nvidia", count: "all", capabilities: ["gpu"] }] },
          },
        },
      });
    }
  });

  it("leaves Laya on the CPU without an NVIDIA GPU", () => {
    for (const value of [undefined, "", "off", "cpu"]) expect(laya(value)).toBeUndefined();
    expect(parse(renderOverride({ status: "first-run", ...base }, [], undefined, OFF))).toEqual({
      services: {},
    });
  });
});
