import { describe, expect, it } from "vitest";
import { parse } from "yaml";
import { InvalidConfigError, renderOverride } from "./genOverride.ts";

const base = { file: "/Users/me/.majhi/majhi.yaml", home: "/Users/me" };

describe("renderOverride", () => {
  it("mounts every root at the same path, and survives spaces and colons", () => {
    const roots = [
      "/Users/me/Work",
      "/Users/me/My Projects/client work",
      "/Volumes/Ext: Disk/code",
      "/Users/me/#x",
    ];
    const text = renderOverride({
      status: "loaded",
      ...base,
      config: { workspaces: roots, tasksDir: "/Users/me/Work/.majhi" },
    });

    expect(text).toMatch(/^# Generated by majhi/);
    expect(parse(text)).toEqual({
      services: {
        server: {
          volumes: [
            "/Users/me/Work:/Users/me/Work",
            "/Users/me/My Projects/client work:/Users/me/My Projects/client work",
            { type: "bind", source: "/Volumes/Ext: Disk/code", target: "/Volumes/Ext: Disk/code" },
            "/Users/me/#x:/Users/me/#x",
          ],
        },
      },
    });
  });

  it("prints a valid override with no mounts on first run", () => {
    const text = renderOverride({ status: "first-run", ...base });
    expect(text).toContain("no extra mounts");
    expect(parse(text)).toEqual({ services: {} });
  });

  it("refuses an invalid config", () => {
    expect(() => renderOverride({ status: "invalid", ...base, errors: ["workspaces: Required"] })).toThrow(
      InvalidConfigError,
    );
  });
});
