import { isAbsolute, normalize, relative, sep } from "node:path";
import type { ConfigState } from "@majhi/shared";
import { Document } from "yaml";

/** Service in docker-compose.yml that gets the workspace mounts. */
export const SERVER_SERVICE = "server";

/** Service in docker-compose.yml that runs Laya in Docker (SPEC 5.12). */
export const LAYA_SERVICE = "laya";

/** The agent socket Docker Desktop and OrbStack give containers on macOS: the default. */
export const HOST_SERVICES_SOCKET = "/run/host-services/ssh-auth.sock";

/** Where an agent socket from outside `~/.majhi` is mounted in the server. */
export const AGENT_TARGET = "/run/ssh-agent.sock";

export class InvalidConfigError extends Error {
  constructor(readonly errors: string[]) {
    super("majhi.yaml is invalid");
  }
}

export interface OverrideOptions {
  /** `MAJHI_SSH_AGENT`: the host's agent socket. Unset or empty is HOST_SERVICES_SOCKET; `off` is none. */
  sshAgent?: string | undefined;
  /** `MAJHI_HOME`, at the same path in the server as on the host. */
  majhiHome?: string | undefined;
  /** `MAJHI_LAYA_GPU`: `nvidia` gives Laya the GPU. */
  layaGpu?: string | undefined;
}

/**
 * A public key mount source. Only `.pub` files may be mounted: OpenSSH reads
 * `<IdentityFile>.pub` to pick the matching key from the agent when the private
 * file is missing, so `IdentitiesOnly yes` works without a private key here.
 */
export function isPublicKeyPath(path: string): boolean {
  return path.startsWith("/") && path.endsWith(".pub") && !path.includes("\n");
}

/** True when `path` is inside `folder`, not the folder itself (so `~/.majhi-old` is not in `~/.majhi`). */
function isInside(path: string, folder: string): boolean {
  const rel = relative(folder, path);
  return rel !== "" && rel !== ".." && !rel.startsWith(`..${sep}`) && !isAbsolute(rel);
}

/**
 * How the server reaches the host's SSH agent (see DECISIONS). A socket under `~/.majhi` is
 * already in the server through that mount, so it only needs `SSH_AUTH_SOCK`. Any other socket is
 * mounted at AGENT_TARGET, as the base compose file did before.
 */
function agentService(options: OverrideOptions): { volume?: unknown; socket: string } | undefined {
  const value = options.sshAgent?.trim() || HOST_SERVICES_SOCKET;
  if (value === "off") return undefined;
  if (!isAbsolute(value) || /[\0\r\n]/.test(value)) {
    throw new Error("MAJHI_SSH_AGENT must be an absolute path to a socket, or off.");
  }
  const path = normalize(value);
  if (options.majhiHome !== undefined && isInside(path, options.majhiHome)) return { socket: path };
  // The short `src:dst` form cannot hold a path with a colon. Use the long form for those.
  const volume = path.includes(":")
    ? { type: "bind", source: path, target: AGENT_TARGET }
    : `${path}:${AGENT_TARGET}`;
  return { volume, socket: AGENT_TARGET };
}

/** Laya's GPU: every NVIDIA device, and laya-serve told to use it. */
function layaService(options: OverrideOptions): Record<string, unknown> | undefined {
  if (options.layaGpu?.trim().toLowerCase() !== "nvidia") return undefined;
  return {
    environment: { LAYA_DEVICE: "cuda" },
    deploy: {
      resources: { reservations: { devices: [{ driver: "nvidia", count: "all", capabilities: ["gpu"] }] } },
    },
  };
}

/**
 * Renders `docker-compose.override.yml`: one bind mount per workspace root,
 * at the same absolute path inside the container, so paths match everywhere,
 * a read-only mount for each SSH public key the host has, the host's SSH agent
 * and, with an NVIDIA GPU, Laya's GPU. `sshPublicKeys` comes from the host,
 * which alone can tell which files exist. A source that is not a `.pub` path is
 * refused: a private key must never be mounted.
 */
export function renderOverride(
  state: ConfigState,
  sshPublicKeys: readonly string[] = [],
  dockerGid?: number,
  options: OverrideOptions = {},
): string {
  if (state.status === "invalid") throw new InvalidConfigError(state.errors);
  const roots = state.status === "loaded" ? state.config.workspaces : [];
  const badKey = sshPublicKeys.find((k) => !isPublicKeyPath(k));
  if (badKey !== undefined) throw new Error(`Refusing to mount ${badKey}: only .pub files are mounted`);
  const keys = [...new Set(sshPublicKeys)].sort();
  const agent = agentService(options);
  const laya = layaService(options);
  const header = [` Generated by majhi from ${state.file}. Do not edit.`, " Run `make up` to regenerate it."];

  if (roots.length === 0 && keys.length === 0 && dockerGid === undefined && !agent && !laya) {
    const doc = new Document({ services: {} });
    doc.commentBefore = [
      ...header,
      " No workspace roots in majhi.yaml yet, so there are no extra mounts.",
    ].join("\n");
    return doc.toString();
  }

  // The short `src:dst` form cannot hold a path with a colon. Use the long form for those.
  const volumes: unknown[] = roots.map((root) =>
    root.includes(":") ? { type: "bind", source: root, target: root } : `${root}:${root}`,
  );
  for (const key of keys) volumes.push({ type: "bind", source: key, target: key, read_only: true });
  if (agent?.volume !== undefined) volumes.push(agent.volume);
  const server: Record<string, unknown> = {};
  if (volumes.length > 0) server.volumes = volumes;
  if (agent !== undefined) server.environment = { SSH_AUTH_SOCK: agent.socket };
  // majhi starts agent runners through the Docker socket; its group lets the owner's uid use it.
  if (dockerGid !== undefined) server.group_add = [String(dockerGid)];
  const services: Record<string, unknown> = {};
  if (Object.keys(server).length > 0) services[SERVER_SERVICE] = server;
  if (laya !== undefined) services[LAYA_SERVICE] = laya;
  const doc = new Document({ services });
  doc.commentBefore = header.join("\n");
  return doc.toString();
}
